import type { Category } from "@prisma/client";
import Head from "next/head";
import type { ChangeEvent, Dispatch, FormEvent, SetStateAction } from "react";
import { useState } from "react";
import { trpc } from "../utils/trpc";

const ProductPage = () => {
  const [name, setName] = useState("");
  const [imgsSrc, setImgsSrc] = useState<string>("");
  const [showForm, setShowForm] = useState(false);
  const [showFormUpdate, setShowFormUpdate] = useState(false);
  const [selectItem, setSelectItem] = useState<Category>();
  const [loading, setLoading] = useState(false);

  const utils = trpc.useContext();
  const categorys = trpc.category.getAll.useQuery(undefined, {
    keepPreviousData: true,
  });
  const deleteItem = trpc.category.delete.useMutation({
    onSettled() {
      utils.category.invalidate();
    },
  });
  const create = trpc.category.create.useMutation({
    onSettled() {
      utils.category.invalidate();
    },
  });

  function onChangeFile(e: ChangeEvent<HTMLInputElement>) {
    if (!e.target.files) return;
    for (const file of e?.target?.files) {
      const reader = new FileReader();
      reader.readAsDataURL(file);
      reader.onload = () => {
        setImgsSrc(reader.result as string);
      };
      reader.onerror = () => {
        console.log(reader.error);
      };
    }
  }

  function handleUpdate(data: Category) {
    setSelectItem(data);
    setShowFormUpdate(true);
  }

  function handleDelete(id: string) {
    setLoading(true);
    deleteItem.mutate({ id });
    setLoading(false);
  }

  function handleSubmit(e: FormEvent<HTMLFormElement>) {
    e.preventDefault();
    setLoading(true);
    const data = {
      name,
      files: imgsSrc,
    };
    create.mutate(data);
    reset();
  }

  function reset() {
    setName("");
    setImgsSrc("");
    setShowForm(false);
    setLoading(false);
  }

  return (
    <main className="mx-auto max-w-screen-2xl px-8">
      <Head>
        <title>Muhammad Sony Fauzi - Category </title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {showForm && (
        <form onSubmit={handleSubmit} className="flex flex-col gap-4">
          <div className="mr-4 flex justify-between">
            <h2 className="text-2xl font-bold uppercase ">Create Category</h2>
            <button
              onClick={() => setShowForm(false)}
              className="rounded bg-rose-300 px-4 py-2 text-rose-900 hover:bg-rose-400"
              disabled={loading}
            >
              Cancel Create
            </button>
          </div>
          <input
            type="text"
            placeholder="Product Name"
            value={name}
            onChange={(e) => setName(e.target.value)}
          />
          <input type="file" placeholder="Image" onChange={onChangeFile} />

          <button
            type="submit"
            className="rounded bg-green-300 px-4 py-2 text-green-900 hover:bg-green-400"
          >
            {loading ? "Loading..." : "Submit"}
          </button>
        </form>
      )}

      {!showForm && !showFormUpdate && (
        <div className="mr-4 flex justify-between pb-4">
          <h2 className="text-2xl font-bold uppercase ">Category </h2>
          <button
            onClick={() => setShowForm(true)}
            className="rounded bg-green-300 px-4 py-2 text-green-900 hover:bg-green-400"
            disabled={loading}
          >
            Create
          </button>
        </div>
      )}

      {!showForm && !showFormUpdate && (
        <section>
          <table className="w-full">
            <thead className="border">
              <tr>
                <th className="border">No</th>
                <th className="border">Name</th>
                <th className="border">slug</th>
                <th className="border">asset id</th>
                <th className="border">Image</th>
                <th className="border">Action</th>
              </tr>
            </thead>
            <tbody>
              {categorys.data?.map((category, index) => (
                <tr key={category.id}>
                  <td className="border">{index + 1}</td>
                  <td className="border">{category.category_name}</td>
                  <td className="border">{category.category_slug}</td>
                  <td className="border">{category.asset_id}</td>
                  <td className="border">
                    <picture>
                      <img
                        src={category.assetId.path}
                        alt={category.category_name}
                        className="h-[100px] w-[100px]"
                      />
                    </picture>
                  </td>
                  <td className="border">
                    <div className="flex gap-4 px-2">
                      <button
                        className="rounded bg-blue-400 px-4 py-2 
                      text-blue-900 hover:bg-blue-400"
                        onClick={() => handleUpdate(category)}
                        disabled={loading}
                      >
                        {loading ? "Loading..." : "Edit"}
                      </button>
                      <button
                        className="rounded bg-red-400 px-4 py-2 
                      text-red-900 hover:bg-red-400"
                        onClick={() => handleDelete(category.id)}
                        disabled={loading}
                      >
                        {loading ? "Loading..." : "Delete"}
                      </button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </section>
      )}

      {showFormUpdate && (
        <Update data={selectItem as Category} setShow={setShowFormUpdate} />
      )}
    </main>
  );
};
interface UpdateProps {
  data: Category;
  setShow: Dispatch<SetStateAction<boolean>>;
}
const Update = ({ data, setShow }: UpdateProps) => {
  const [name, setName] = useState(data.category_name);
  const [imgsSrc, setImgsSrc] = useState<string>("");
  const [loading, setLoading] = useState(false);

  const utils = trpc.useContext();
  const update = trpc.category.update.useMutation({
    onSettled() {
      utils.product.invalidate();
    },
  });

  function onChangeFile(e: ChangeEvent<HTMLInputElement>) {
    if (!e.target.files) return;
    for (const file of e?.target?.files) {
      const reader = new FileReader();
      reader.readAsDataURL(file);
      reader.onload = () => {
        setImgsSrc(reader.result as string);
      };
      reader.onerror = () => {
        console.log(reader.error);
      };
    }
  }

  function handleSubmit(e: FormEvent<HTMLFormElement>) {
    e.preventDefault();
    setLoading(true);
    const input = {
      id: data.id,
      name,
      files: imgsSrc,
    };
    update.mutate(input);
    reset();
  }

  function reset() {
    setName("");
    setLoading(false);
    setShow(false);
  }

  return (
    <section>
      <form onSubmit={handleSubmit} className="flex flex-col gap-4">
        <div className="mr-4 flex justify-between">
          <h2 className="text-2xl font-bold uppercase ">Update Category</h2>
          <button
            onClick={() => setShow(false)}
            className="rounded bg-rose-300 px-4 py-2 text-rose-900 hover:bg-rose-400"
            disabled={loading}
          >
            Cancel Update
          </button>
        </div>
        <input
          type="text"
          placeholder="Product Name"
          value={name}
          onChange={(e) => setName(e.target.value)}
        />
        <input type="file" placeholder="Image" onChange={onChangeFile} />
        <button
          type="submit"
          className="rounded bg-green-300 px-4 py-2 text-green-900 hover:bg-green-400"
        >
          {loading ? "Loading..." : "Submit"}
        </button>
      </form>
    </section>
  );
};

export default ProductPage;
